services:
  # Datenbank: MongoDB
  mongodb:
    image: mongo:latest
    container_name: cheatsheet_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - web

  # Backend: Express API
  api:
    build: ./api
    container_name: cheatsheet_api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./app/src/css:/usr/src/app/src/shared_css:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.cheatsheet-api.rule=Host(`api.urben.dev`)"
      - "traefik.http.routers.cheatsheet-api.entrypoints=websecure"
      - "traefik.http.routers.cheatsheet-api.tls.certresolver=le"
      - "traefik.http.services.cheatsheet-api.loadbalancer.server.port=3030"
    networks:
      - web

  # Frontend: Vite
  frontend:
    build: ./app
    container_name: cheatsheet_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - path: ./.env
        required: true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cheatsheet.rule=Host(`cheatsheet.urben.dev`)"
      - "traefik.http.routers.cheatsheet.entrypoints=websecure"
      - "traefik.http.routers.cheatsheet.tls.certresolver=le"
      - "traefik.http.services.cheatsheet.loadbalancer.server.port=5173"
    networks:
      - web

volumes:
  mongo_data:

networks:
  web:
    external: true