services:
  # Datenbank: MongoDB
  mongodb:
    image: mongo:latest
    container_name: cheatsheet_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend: Express API
  api:
    build: ./api
    container_name: cheatsheet_api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./api/output:/usr/src/app/output
      - ./app/src/css:/usr/src/app/src/shared_css:ro
    env_file:
      - path: ./.env
        required: true

  # Frontend: Vite
  frontend:
    build: ./app
    container_name: cheatsheet_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - path: ./.env
        required: true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

volumes:
  mongo_data: